`id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
	`employee_id` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8_unicode_ci',
	`name` VARCHAR(255) NOT NULL COLLATE 'utf8_unicode_ci',
	`email` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8_unicode_ci',
	`email_verified_at` TIMESTAMP NULL DEFAULT NULL,
	`password` VARCHAR(255) NOT NULL COLLATE 'utf8_unicode_ci',
	`def_pass` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_unicode_ci',
	`two_factor_secret` TEXT NULL DEFAULT NULL COLLATE 'utf8_unicode_ci',
	`two_factor_recovery_codes` TEXT NULL DEFAULT NULL COLLATE 'utf8_unicode_ci',
	`two_factor_confirmed_at` TIMESTAMP NULL DEFAULT NULL,
	`remember_token` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_unicode_ci',
	`created_at` TIMESTAMP NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NULL DEFAULT NULL,
	`dep` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_unicode_ci',
	`groud` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_unicode_ci',
	`login_at` TIMESTAMP NULL DEFAULT NULL,
	`login_count` VARCHAR(50) NOT NULL DEFAULT '0' COLLATE 'utf8_unicode_ci',
	`type` INT(11) NOT NULL DEFAULT '0',